import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'animate.css';
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import React from "react";



const JetBrains = JetBrains_Mono({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Tran Gia Lam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JetBrains.className}>{children}</body>
    </html>
  );
}
